language: python
install: "bash -ex .travis-ocaml.sh; opam install core dune odoc -y; eval $(opam env)"
env:
  - OCAML_VERSION=4.06
script: "opam install . -y"

branches: 
  only:
    - master

before_deploy:
  - dune build @doc

deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: ./_build/default/_doc/_html
  repo: katshun0307/katshun0307.github.io
  on:
    branch: master
  target_branch: master
  deployment-file: ./docs/mutables
